user:
  name:
    maximum: 50
  email:
    maximum: 100
  password:
    minimum: 6
product:
  name:
    minimum: 4
  price:
    minimum: 0
  quantity:
    minimum: 0
  pagination: 6
feedback:
  subject:
    maximum: 100
product_order:
  quantity:
    minimum: 0
  total_price:
    minimum: 0
rating:
  value:
    minimum: 0
    maximum: 6
